### ISSUE TITLE
FDT's not completely licensed under  X11

### ISSUE THREAD

**Issue by kallisti5** [TinkerBoard/debian_u-boot#1]
A bunch of the FDT's are dual licensed under X11 (which is great because we can add support for RockChip boards via FDT's in our open source MIT-licensed OS)

However, not all of the FDT files are dual GPL + X11 licensed:

* https://github.com/TinkerBoard/debian_u-boot/blob/linux4.4-rk3288/arch/arm/dts/rk3288.dtsi
* https://github.com/TinkerBoard/debian_u-boot/blob/linux4.4-rk3288/arch/arm/dts/rk3036.dtsi

Any chance of licensing these as dual GPL + X11 as well?
If you went with the MIT license this wouldn't be an issue (and you wouldn't have to dual-license)

Thanks for making RockChip is a great SOC for open-source development!

 -- Alex

**Comment by TinkerTeam** [comment]
Hi @kallisti5 

After the discussion with Rockchip.
We got the authorized to provide the dual license GPL + X11 for the https://github.com/TinkerBoard/debian_u-boot/blob/linux4.4-rk3288/arch/arm/dts/rk3288.dtsi at 09e0c29ead502f5ff7510d32dbbb7d1f3eee1fde
