### ISSUE TITLE
U-Boot Does Not Load Overlays

### ISSUE THREAD

**Issue by sghazagh** [TinkerBoard/debian_u-boot#2]
Hi,
In your new settings (Debian OS 2.0.1), you have set the kernel to generate overlays and you have used them in your Image.
These overlays needs to be loaded through "hw_intf.conf".
For instance:  **intf:dts_overlay=/w1-gpio.dtbo**

However, the latest commit on this repository for U-Boot cannot load those overlays.
Please update th u-boot branch and release a working U-Boot commit compatible with your recent Debian Image version 2.0.1.

Thanks

**Comment by jamess-huang** [comment]
We have been released the v2.0.1, and the later image version of u-boot.
But we modified the format of the overlay after the v2.0.3 image (include v2.0.3)
Before V2.0.1 the overlay should located at **/boot** folder and the hw_intf.conf should be like below
**intf:dts_overlay=/w1-gpio.dtbo**

After V2.0.3 the overlay should located at **/boot/overlays** folder and the hw_intf.conf should be like below
~~**intf:dtoverlay=w1-gpio.dtbo**~~
**intf:dtoverlay=w1-gpio** (update, fix typo)

**Comment by sghazagh** [comment]
Dear James/All,
I can confirm that the latest u-boot 2.0.4 is working fine, however, the format of overlays inside hw_intf.conf file is wrong with the way Mr. James has mentioned above.
The correct format is without .dtbo at the end:
**intf:dtoverlay=w1-gpio**

If you mention the .dtbo at the end of the **dtoverlay** command, u-boot looks for file "**w1-gpio.dtbo.dtbo**" which is wrong.

**Comment by jamess-huang** [comment]
Sorry, it's my typo. The example we provided in the hw_intf.conf is right.
It should be like the below at the V2.0.3 image.
**intf:dtoverlay=w1-gpio**

**Comment by sghazagh** [comment]
Dear James,
Can you just confirm if the latest Kernel also have the 1-Wire patch or not?
I only have tested the Kernel with manual Patch you had provided me long time ago. Does that patch has applied to the Kernel source as well?
Thanks,
Saeid

**Comment by jamess-huang** [comment]
Since we fixed this issue by several commits, I just merged all of them into 1 commit and provided it to you. So you can not find the commit id I provided to you before, but I am sure that all of the modified codes are in our github code base.

**Comment by sghazagh** [comment]
That would work as far as a fresh kernel compile get all the changes in place.
Thanks
