### ISSUE TITLE
Broken Link in Description

### ISSUE THREAD

**Issue by star-ga** [TinkerBoard/debian_u-boot#4]
Pre-built (and tested) images are available from:
ftp://ftp.denx.de/pub/u-boot/images/  - broken link!

**Comment by TinkerTeam** [comment]
Hi @cputer,

That README we do not change it, is fork from upstream [http://git.denx.de/u-boot.git](http://git.denx.de/u-boot.git)'s [README](http://git.denx.de/?p=u-boot.git;a=blob;f=README;hb=HEAD)

So ,you probably need to open ticket at upstream.
Thanks.

**Comment by sghazagh** [comment]
All the files are located here: [ftp://ftp.denx.de/pub/u-boot/](ftp://ftp.denx.de/pub/u-boot/)
