### ISSUE TITLE
Build debian_u-boot fails

### ISSUE THREAD

**Issue by sv1eia** [TinkerBoard/debian_u-boot#8]
Hi,

Using Ubuntu Focal virtual machine for all Linux compiles and trying to build the Tinkerboard debian_u-boot
following these
[https://tinker-board.asus.com/doc_tb.html#os/](url)
and
[https://tinkerboarding.co.uk/wiki/index.php/Software#How_to_build_Kernel.2FU-boot_source_code](url)

 but it fails  upon execution of
make CROSS_COMPILE=arm-linux-gnueabihf- O=miniarm-rk3288 tinker-rk3288_defconfig all -j4

`  CC      lib/efi_loader/efi_boottime.o

  CC      lib/efi_loader/efi_runtime.o

  CC      lib/efi_loader/efi_console.o

  CC      lib/efi_loader/efi_memory.o

  CC      lib/efi_loader/efi_disk.o

  CC      lib/efi_loader/efi_net.o

  CC      lib/efi_loader/efi_smbios.o

  LD      lib/efi_loader/built-in.o

  CC      lib/efi_loader/helloworld.o

  LD      lib/efi_loader/helloworld.so

arm-linux-gnueabihf-ld.bfd: error: linker script file '../arch/arm/lib/elf_arm_efi.lds' appears multiple times

make[4]: *** [scripts/Makefile.lib:382: lib/efi_loader/helloworld.so] Error 1

make[3]: *** [../scripts/Makefile.build:425: lib/efi_loader] Error 2

make[2]: *** [../Makefile:1271: lib] Error 2

make[1]: *** [/home/christos/tinkerboard/debian_u-boot/Makefile:460: __build_one_by_one] Error 2

make[1]: Leaving directory '/home/christos/tinkerboard/debian_u-boot/miniarm-rk3288'

make: *** [Makefile:150: sub-make] Error 2

christos@ubuntu:~/tinkerboard/debian_u-boot$ uname -a

Linux ubuntu 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

christos@ubuntu:~/tinkerboard/debian_u-boot$ 

`

Are there any specific instructions on what prerequisites are needed, on what platform and how to build the debian_u-boot ?

**Comment by asus-leslieyu** [comment]
There are issues to build with Ubuntu Focal. Please use the following Docker environment to build with Xenial.

https://github.com/asus-iot/asus-docker-env

**Comment by sv1eia** [comment]
Installed docker in Focal and followed the instructions in https://github.com/asus-iot/asus-docker-env

When I tried a new compile inside the docker container got the same error

  CC      lib/efi_loader/efi_smbios.o
  LD      lib/efi_loader/built-in.o
  CC      lib/efi_loader/helloworld.o
  LD      lib/efi_loader/helloworld.so
arm-linux-gnueabihf-ld.bfd: error: linker script file '../arch/arm/lib/elf_arm_efi.lds' appears multiple times
make[4]: *** [scripts/Makefile.lib:382: lib/efi_loader/helloworld.so] Error 1
make[3]: *** [../scripts/Makefile.build:425: lib/efi_loader] Error 2
make[2]: *** [../Makefile:1271: lib] Error 2
make[1]: *** [/source/debian_u-boot/Makefile:460: __build_one_by_one] Error 2
make[1]: Leaving directory '/source/debian_u-boot/miniarm-rk3288'
make: *** [Makefile:150: sub-make] Error 2
christos@4b630aa2e5dc:/source/debian_u-boot$


Is there any step by step guide on how to use the aforementioned docker environment in order to build the tinkerboard uboot and kernel?

**Comment by asus-leslieyu** [comment]
Hi,

Did you use the following command to change the Dockfile to the one from xenial? The default one is from focal. Please change it to from xenial for Tinker Board (S). Thanks a lot!

asus_docker_env_set_dockerfile ./xenial/Dockerfile

**Comment by sv1eia** [comment]
As I mentioned already, the build system is Ubuntu Focal, so according to https://github.com/asus-iot/asus-docker-env I do not need to switch to Xenial

christos@ubuntu:~/tinkerboard/asus-docker-env$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
christos@ubuntu:~/tinkerboard/asus-docker-env$ 

Do you want me to regardless try to switch the docker to xenial with 
asus_docker_env_set_dockerfile ./xenial/Dockerfile

??

**Comment by sv1eia** [comment]
Ok, switched the docker container to xenial and now uboot compiles just fine.
Thanks for the help.

**Comment by asus-leslieyu** [comment]
Yes, regardless the host is focal or not, need to use Dockerfile based on xenial since there are issues related to tool chains from focal with the source code.
